Added linked list in data structures
huangsam/ultimate-python pull request #25
Opened 2020-10-18 07:22 UTC by SaShaShady

---

**Describe the change**
I added the execution of linked list in the data structures folder

2020-10-19 02:00 UTC, huangsam commented
@SaShaShady thanks for the submission! Looks like the `Lint` task failed in the CircleCI build.

2020-10-19 02:24 UTC, huangsam requested changes
I like how the code seems to be fairly logical. A couple of points:

- This module does not have a `main` routine yet
- This module uses `print` statements and no `assert` statements
- This module is not referenced in the `README.md`

Last but not least, [collections.deque](https://docs.python.org/3/library/collections.html#collections.deque) already does most of what you're proposing here. I think it's generally better to reuse builtin libraries. Perhaps this could be a lesson on `ultimatepython/data_structures/deque.py`. Would you be interested in taking a stab at this?

2020-10-19 02:24 UTC, huangsam commented on ultimatepython/data_structures/linkedlist.py
> +class CLinkedList:
What is the rationale for this class being called `CLinkedList` instead of simply `LinkedList`?

2020-10-19 02:24 UTC, huangsam commented on ultimatepython/data_structures/linkedlist.py
> +class Node:
Consider using `ListNode` to stay consistent with the `LinkedList` class.

2020-10-19 02:24 UTC, huangsam commented on ultimatepython/data_structures/linkedlist.py
> +                temp = temp.nextval
Please do not write methods that utilize `print` statements. Notice the following statement in the [contribution guidelines](https://github.com/huangsam/ultimate-python/blob/master/CONTRIBUTING.md#python-modules):

> Each module has a name that corresponds to a topic and explores concepts with assert statements.

2020-10-19 02:24 UTC, huangsam commented on ultimatepython/data_structures/linkedlist.py
> +    def AtBeginning(self, newdata):
I like what is being implied with `AtBeginning`. The problem is that the method does not have a verb in it which means it misses the intent. Furthermore, Python methods are usually written as `this_kind_of_style`.

I'd like to propose the following option: `insert_left` which seems to be what you're going for.

2020-10-19 02:24 UTC, huangsam commented on ultimatepython/data_structures/linkedlist.py
> +
Spacing like this is unnecessary.

2020-10-19 02:24 UTC, huangsam commented on ultimatepython/data_structures/linkedlist.py
> +            NewNode = Node(newdata)
`NewNode` should be renamed to `new_node`.

2020-10-19 02:24 UTC, huangsam commented on ultimatepython/data_structures/linkedlist.py
> +        self.preval = None
Any variable or attribute that represents more than one English word should be separated as follows:

- `data_val`
- `next_val`
- `prev_val`

2020-10-19 02:24 UTC, huangsam commented on ultimatepython/data_structures/linkedlist.py
> +    def AtEnd(self, newdata):
I propose `insert_right`.

2020-10-19 02:24 UTC, huangsam commented on ultimatepython/data_structures/linkedlist.py
> +    def removeStart(self):
I propose `remove_left`.

2020-10-19 02:24 UTC, huangsam commented on ultimatepython/data_structures/linkedlist.py
> +    def removeEnd(self):
I propose `remove_right`.

2020-10-19 02:24 UTC, huangsam commented on ultimatepython/data_structures/linkedlist.py
> +    def removeMiddle(self, removeKey):
I propose `remove_val`. Also this doesn't seem to handle the case where `head` is removed. And `removeKey` should be named as `remove_key`.

2020-10-20 04:45 UTC, huangsam approved these changes
Looks better this way

2020-10-20 05:18 UTC, huangsam commented
Looks like the CircleCI build is not working successfully despite the valid code. I'm going to go ahead and commit the changes directly. Thanks for the pull request! Feel free to throw another pull request when you have another idea in mind.

2020-10-20 05:18 UTC, closed without merging

2020-10-20 05:27 UTC, SaShaShady commented
Hello,
Thank you so much! Going through a lot of exams right now, so will
definitely think about it later.

On Tue, Oct 20, 2020 at 10:49 AM Samuel Huang <notifications@github.com>
wrote:

> Looks like the CircleCI build is not working successfully despite the
> valid code. I'm going to go ahead and commit the changes directly. Thanks
> for the pull request! Feel free to throw another pull request when you have
> another idea in mind.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/huangsam/ultimate-python/pull/25#issuecomment-712596158>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMMUJDC7XTAQS5QWJ22KMQTSLUMUVANCNFSM4SU4XW2A>
> .
>