Create priority_queue.py
huangsam/ultimate-python pull request #94
Opened 2023-10-10 16:46 UTC by Mayureshd-18

*Please read the [contributing guidelines](https://github.com/huangsam/ultimate-python/blob/master/CONTRIBUTING.md) before submitting a pull request.*

---

**Describe the change**
A clear and concise description of what the change is.

**Additional context**
Add any other context or screenshots about the pull request here.

2023-10-10 16:54 UTC, Mayureshd-18 commented
Didnt write the name of the file as heapq.py as it may cause circular imports error

2023-10-13 05:53 UTC, Mayureshd-18 commented
@huangsam Made the requested changes. Please review.

2023-10-13 09:18 UTC, huangsam requested changes
In general a good resource for this is:
https://docs.python.org/3/library/heapq.html#theory

Please make it such that folks understand what's happening under the hood. Otherwise, people would just prefer using the `list.sort` or `sorted` method. Lots of Python devs want sorting to "just work" - so I don't think sharing just the steps for Heap usage is enough

2023-10-13 09:18 UTC, huangsam commented on ultimatepython/data_structures/priority_queue.py
> +    heapq.heapify(heap)
Should we share a video or informational about what `heapify` does under the hood?

2023-10-13 09:18 UTC, huangsam commented on ultimatepython/data_structures/priority_queue.py
> +    assert heap == [1, 1, 2, 3, 5, 9, 4]
Should we share what it means for a Python list to be in min heap order?

2023-10-13 09:18 UTC, huangsam commented on ultimatepython/data_structures/priority_queue.py
> +    # Add a new element to the heap using heapq.heappush()
Again, should we be sharing what happens under the hood for `heappush`?

2023-10-13 09:18 UTC, huangsam commented on ultimatepython/data_structures/priority_queue.py
> +# By following these steps, you can effectively create, modify, and work with min heaps using the heapq module in Python.
Perhaps this content should be put at the very top of the module in the module's docstring

2023-10-13 09:18 UTC, huangsam commented on ultimatepython/data_structures/priority_queue.py
> +    """
This should be put at the top of the module, along with the content at the bottom of the file

2023-10-21 21:42 UTC, huangsam commented
This PR has been around for too long. Let's close it for now. If you would like to make a new PR again, feel free to submit another one. Thanks again for the submission

2023-10-21 21:42 UTC, closed without merging